// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/protobuf.proto

// Changed package to 'pb' to avoid confusion since it contains more than just users

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_protobuf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{0}
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_proto_protobuf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_proto_protobuf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *UserId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressId) Reset() {
	*x = AddressId{}
	mi := &file_proto_protobuf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressId) ProtoMessage() {}

func (x *AddressId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressId.ProtoReflect.Descriptor instead.
func (*AddressId) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *AddressId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_protobuf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_protobuf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_protobuf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_protobuf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_protobuf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_proto_protobuf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{9}
}

func (x *UserListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Address struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RawAddress        string                 `protobuf:"bytes,2,opt,name=raw_address,json=rawAddress,proto3" json:"raw_address,omitempty"`
	NormalizedAddress string                 `protobuf:"bytes,3,opt,name=normalized_address,json=normalizedAddress,proto3" json:"normalized_address,omitempty"`
	Coordinates       *Coordinates           `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Accuracy          string                 `protobuf:"bytes,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Source            string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_protobuf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{10}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetRawAddress() string {
	if x != nil {
		return x.RawAddress
	}
	return ""
}

func (x *Address) GetNormalizedAddress() string {
	if x != nil {
		return x.NormalizedAddress
	}
	return ""
}

func (x *Address) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Address) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *Address) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RawAddress    string                 `protobuf:"bytes,2,opt,name=raw_address,json=rawAddress,proto3" json:"raw_address,omitempty"`
	Coordinates   *Coordinates           `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Accuracy      string                 `protobuf:"bytes,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_proto_protobuf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAddressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAddressRequest) GetRawAddress() string {
	if x != nil {
		return x.RawAddress
	}
	return ""
}

func (x *CreateAddressRequest) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *CreateAddressRequest) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *CreateAddressRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RawAddress    string                 `protobuf:"bytes,2,opt,name=raw_address,json=rawAddress,proto3" json:"raw_address,omitempty"`
	Coordinates   *Coordinates           `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Accuracy      string                 `protobuf:"bytes,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_protobuf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetRawAddress() string {
	if x != nil {
		return x.RawAddress
	}
	return ""
}

func (x *UpdateAddressRequest) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *UpdateAddressRequest) GetAccuracy() string {
	if x != nil {
		return x.Accuracy
	}
	return ""
}

func (x *UpdateAddressRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AddressListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListRequest) Reset() {
	*x = AddressListRequest{}
	mi := &file_proto_protobuf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListRequest) ProtoMessage() {}

func (x *AddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListRequest.ProtoReflect.Descriptor instead.
func (*AddressListRequest) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{13}
}

func (x *AddressListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AddressListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AddressListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListData) Reset() {
	*x = AddressListData{}
	mi := &file_proto_protobuf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListData) ProtoMessage() {}

func (x *AddressListData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListData.ProtoReflect.Descriptor instead.
func (*AddressListData) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{14}
}

func (x *AddressListData) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type AddressListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AddressListData       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListResponse) Reset() {
	*x = AddressListResponse{}
	mi := &file_proto_protobuf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListResponse) ProtoMessage() {}

func (x *AddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protobuf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListResponse.ProtoReflect.Descriptor instead.
func (*AddressListResponse) Descriptor() ([]byte, []int) {
	return file_proto_protobuf_proto_rawDescGZIP(), []int{15}
}

func (x *AddressListResponse) GetData() *AddressListData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddressListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AddressListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_proto_protobuf_proto protoreflect.FileDescriptor

const file_proto_protobuf_proto_rawDesc = "" +
	"\n" +
	"\x14proto/protobuf.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\a\n" +
	"\x05Empty\"G\n" +
	"\vCoordinates\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\x18\n" +
	"\x06UserId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1b\n" +
	"\tAddressId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"b\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"r\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\x10UserListResponse\x12\x1e\n" +
	"\x05users\x18\x01 \x03(\v2\b.pb.UserR\x05users\"\xd0\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vraw_address\x18\x02 \x01(\tR\n" +
	"rawAddress\x12-\n" +
	"\x12normalized_address\x18\x03 \x01(\tR\x11normalizedAddress\x121\n" +
	"\vcoordinates\x18\x04 \x01(\v2\x0f.pb.CoordinatesR\vcoordinates\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\tR\baccuracy\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\xb7\x01\n" +
	"\x14CreateAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vraw_address\x18\x02 \x01(\tR\n" +
	"rawAddress\x121\n" +
	"\vcoordinates\x18\x03 \x01(\v2\x0f.pb.CoordinatesR\vcoordinates\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\tR\baccuracy\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xae\x01\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vraw_address\x18\x02 \x01(\tR\n" +
	"rawAddress\x121\n" +
	"\vcoordinates\x18\x03 \x01(\v2\x0f.pb.CoordinatesR\vcoordinates\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\tR\baccuracy\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\">\n" +
	"\x12AddressListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"<\n" +
	"\x0fAddressListData\x12)\n" +
	"\taddresses\x18\x01 \x03(\v2\v.pb.AddressR\taddresses\"h\n" +
	"\x13AddressListResponse\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.pb.AddressListDataR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page2\x97\x03\n" +
	"\vUserService\x12C\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\b.pb.User\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x127\n" +
	"\aGetUser\x12\n" +
	".pb.UserId\x1a\b.pb.User\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}\x12H\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\b.pb.User\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/users/{id}\x12;\n" +
	"\n" +
	"DeleteUser\x12\n" +
	".pb.UserId\x1a\t.pb.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/users/{id}\x12?\n" +
	"\tListUsers\x12\t.pb.Empty\x1a\x14.pb.UserListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12B\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login2\x9d\x03\n" +
	"\x0eAddressService\x12P\n" +
	"\rCreateAddress\x12\x18.pb.CreateAddressRequest\x1a\v.pb.Address\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/addresses\x12D\n" +
	"\n" +
	"GetAddress\x12\r.pb.AddressId\x1a\v.pb.Address\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/addresses/{id}\x12U\n" +
	"\rUpdateAddress\x12\x18.pb.UpdateAddressRequest\x1a\v.pb.Address\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/addresses/{id}\x12E\n" +
	"\rDeleteAddress\x12\r.pb.AddressId\x1a\t.pb.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/addresses/{id}\x12U\n" +
	"\vListAddress\x12\x16.pb.AddressListRequest\x1a\x17.pb.AddressListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/addressesB$Z\"github.com/imimran/go-grpc-auth/pbb\x06proto3"

var (
	file_proto_protobuf_proto_rawDescOnce sync.Once
	file_proto_protobuf_proto_rawDescData []byte
)

func file_proto_protobuf_proto_rawDescGZIP() []byte {
	file_proto_protobuf_proto_rawDescOnce.Do(func() {
		file_proto_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_protobuf_proto_rawDesc), len(file_proto_protobuf_proto_rawDesc)))
	})
	return file_proto_protobuf_proto_rawDescData
}

var file_proto_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_protobuf_proto_goTypes = []any{
	(*Empty)(nil),                // 0: pb.Empty
	(*Coordinates)(nil),          // 1: pb.Coordinates
	(*UserId)(nil),               // 2: pb.UserId
	(*AddressId)(nil),            // 3: pb.AddressId
	(*User)(nil),                 // 4: pb.User
	(*CreateUserRequest)(nil),    // 5: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),    // 6: pb.UpdateUserRequest
	(*LoginRequest)(nil),         // 7: pb.LoginRequest
	(*LoginResponse)(nil),        // 8: pb.LoginResponse
	(*UserListResponse)(nil),     // 9: pb.UserListResponse
	(*Address)(nil),              // 10: pb.Address
	(*CreateAddressRequest)(nil), // 11: pb.CreateAddressRequest
	(*UpdateAddressRequest)(nil), // 12: pb.UpdateAddressRequest
	(*AddressListRequest)(nil),   // 13: pb.AddressListRequest
	(*AddressListData)(nil),      // 14: pb.AddressListData
	(*AddressListResponse)(nil),  // 15: pb.AddressListResponse
}
var file_proto_protobuf_proto_depIdxs = []int32{
	4,  // 0: pb.UserListResponse.users:type_name -> pb.User
	1,  // 1: pb.Address.coordinates:type_name -> pb.Coordinates
	1,  // 2: pb.CreateAddressRequest.coordinates:type_name -> pb.Coordinates
	1,  // 3: pb.UpdateAddressRequest.coordinates:type_name -> pb.Coordinates
	10, // 4: pb.AddressListData.addresses:type_name -> pb.Address
	14, // 5: pb.AddressListResponse.data:type_name -> pb.AddressListData
	5,  // 6: pb.UserService.CreateUser:input_type -> pb.CreateUserRequest
	2,  // 7: pb.UserService.GetUser:input_type -> pb.UserId
	6,  // 8: pb.UserService.UpdateUser:input_type -> pb.UpdateUserRequest
	2,  // 9: pb.UserService.DeleteUser:input_type -> pb.UserId
	0,  // 10: pb.UserService.ListUsers:input_type -> pb.Empty
	7,  // 11: pb.UserService.Login:input_type -> pb.LoginRequest
	11, // 12: pb.AddressService.CreateAddress:input_type -> pb.CreateAddressRequest
	3,  // 13: pb.AddressService.GetAddress:input_type -> pb.AddressId
	12, // 14: pb.AddressService.UpdateAddress:input_type -> pb.UpdateAddressRequest
	3,  // 15: pb.AddressService.DeleteAddress:input_type -> pb.AddressId
	13, // 16: pb.AddressService.ListAddress:input_type -> pb.AddressListRequest
	4,  // 17: pb.UserService.CreateUser:output_type -> pb.User
	4,  // 18: pb.UserService.GetUser:output_type -> pb.User
	4,  // 19: pb.UserService.UpdateUser:output_type -> pb.User
	0,  // 20: pb.UserService.DeleteUser:output_type -> pb.Empty
	9,  // 21: pb.UserService.ListUsers:output_type -> pb.UserListResponse
	8,  // 22: pb.UserService.Login:output_type -> pb.LoginResponse
	10, // 23: pb.AddressService.CreateAddress:output_type -> pb.Address
	10, // 24: pb.AddressService.GetAddress:output_type -> pb.Address
	10, // 25: pb.AddressService.UpdateAddress:output_type -> pb.Address
	0,  // 26: pb.AddressService.DeleteAddress:output_type -> pb.Empty
	15, // 27: pb.AddressService.ListAddress:output_type -> pb.AddressListResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_protobuf_proto_init() }
func file_proto_protobuf_proto_init() {
	if File_proto_protobuf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_protobuf_proto_rawDesc), len(file_proto_protobuf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_protobuf_proto_goTypes,
		DependencyIndexes: file_proto_protobuf_proto_depIdxs,
		MessageInfos:      file_proto_protobuf_proto_msgTypes,
	}.Build()
	File_proto_protobuf_proto = out.File
	file_proto_protobuf_proto_goTypes = nil
	file_proto_protobuf_proto_depIdxs = nil
}
